name: patteera_readability
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  file_picker: ^10.3.8
  google_fonts: ^6.3.3
  flutter_animate: ^4.5.2
  yaml: ^3.1.3
  flutter_tesseract_ocr: ^0.4.30
  image_picker: ^1.2.1
  dotted_border: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21
  linux: "logo"

flutter_native_splash:
  color: "#1A1B26"
  image: "assets/icon/logo.png"
  android_12:
    image: "assets/icon/logo.png"
    color: "#1A1B26"

flutter:
  uses-material-design: true

  assets:
    - assets/config.yaml
    - assets/words/
    - assets/icon/
